### ISSUE TITLE
Add persist data step to release.js?

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#11]
It would be great if the script that checks for and builds a release for the public site could incorporate the step of persisting changed data from Airtable to JSON.

**Comment by edsu** [comment]
I think that should do it!

**Comment by edsu** [comment]
Whoops I had to make a change  since `npm run release` runs from cron every 5 minutes and we only want `npm run persist` to run when there is an actual build to perform and not every time. 76ddd428eaecdbda304c1c6b25a9115019c3c969
