### ISSUE TITLE
Make sure `release.js` script throws an error if there isn't a new code tag/release

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#16]
I think [this function](https://github.com/umd-mith/mith-static/blob/master/scripts/release.js#L25-L29) is maybe just printing to the log but not also finishing out and throwing an error that will get reported as a failed build. As a result it looks like build process has just gotten stuck and there's no way for most team members to debug.

**Comment by raffazizzi** [comment]
Switching to a different system
