### ISSUE TITLE
Faculty/Staff listing should be alphabetic

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#21]
In the current staging build it is … random? https://umd-mith.github.io/mith-static/people/

**Comment by raffazizzi** [comment]
They are ordered by last name, but in the Airtable Base middle names are bundled with last names. So for example Andrew **W. Smith** was wrongly appearing after Raff **Viglianti**. I have created a separate entry for middle name in the Base (also asked for some clarifications on Slack to be sure). So the next build should look better, at least placing Andrew in the right spot.

However, it could still appear confusing to a new reader... should we sort by first name?

**Comment by raffazizzi** [comment]
@trevormunoz what do you think about sorting by first name? If we don't want further changes, then I think this is fixed and can be closed.

**Comment by trevormunoz** [comment]
@raffazizzi Yes, let's try ordered by first name

**Comment by trevormunoz** [comment]
Let's go with this for now
