### ISSUE TITLE
Issues with past people

### ISSUE THREAD

**Issue by raffazizzi** [umd-mith/mith-static#23]
@trevormunoz and @ssapienza we have [a page for past people](https://mith.umd.edu/people-past/) but I don't thiink it's linked from anywhere at the moment.

* I suggest that we link to it from the people page, after the list of current staff members, but before the affiliates.
* We may want to double check the information on the page. For example Neil Fraistat is listed as 

> Neil Fraistat
> PhD Candidate
> Professor
> Director, 2006–2017

The titles are derived from identities associated with the person on AirTable, but some identities may not be relevant or helpful (such as listing Neil as a PhD Candidate).

**Comment by raffazizzi** [comment]
For the second bullet point, I just pushed a change to only show identities with a start date; it seems to produce a page with much more accurate information

**Comment by trevormunoz** [comment]
+1 to making the past people page visible as @raffazizzi suggests.

Hopefully we can vanquish the data gremlins quickly
