### ISSUE TITLE
Better names for component TS interfaces

### ISSUE THREAD

**Issue by raffazizzi** [umd-mith/mith-static#27]
Currently most TS interfaces for components are just called `Props`. Rename to ComponentName+Props

**Comment by trevormunoz** [comment]
I think I already did this in #24? See [346868b](https://github.com/umd-mith/mith-static/pull/24/commits/346868b0fe6b647c879ab53334424796f3e64eb6)

**Comment by raffazizzi** [comment]
ah sorry!
