### ISSUE TITLE
Sort past people by date

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#29]
Follow up to #23. Sort by leaving date (if exists) otherwise just date

**Comment by trevormunoz** [comment]
Thanks. Just noting that identities are biting us in the 🍑 again. For example, Aleia and Catherine should be reversed in order going by their MITH affiliations

**Comment by trevormunoz** [comment]
Big improvement overall though!

**Comment by raffazizzi** [comment]
Currently this page shows any identity that has both a start and end date. So yes, that must include also non-MITH ones!

Let's factor this into a discussion with @ssapienza to review the handling of people, identities, and their union within a table.
