### ISSUE TITLE
Person page layout broken

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#7]
Styles for person pages (e.g., https://umd-mith.github.io/mith-static/people/grace-babukiika) seem to be defaulting to multi-column and are thus broken on mobile.

**Comment by kirstenkeister** [comment]
@trevormunoz I will take a look. It likely got messed up when I implemented the CSS for Past People, but will fix it regardless.

**Comment by trevormunoz** [comment]
Research items have something similar going on but I figured you were still working on those so I didn't file a bug :)

**Comment by trevormunoz** [comment]
The media query fixes the core issue. Looks like there might still be some wrapping issues, e.g.
<img width="467" alt="Screen Shot 2021-04-15 at 4 00 23 PM" src="https://user-images.githubusercontent.com/351120/114931281-096b0b00-9e04-11eb-8e51-4412c4bc018f.png">

**Comment by kirstenkeister** [comment]
Okay. The screenshot is very helpful! I will investigate and fix.

**Comment by kirstenkeister** [comment]
@trevormunoz Could you review and let me know if this is now displaying properly on your computer?

**Comment by trevormunoz** [comment]
Thanks @kirstenkeister. This looks like a good fix to me.
