### ISSUE TITLE
Affiliate data not displaying

### ISSUE THREAD

**Issue by trevormunoz** [umd-mith/mith-static#9]
See: https://umd-mith.github.io/mith-static/people/#625

**Comment by kirstenkeister** [comment]
@trevormunoz you were 90% of the way there. Her identity needed to be linked to the `identity_as_current` field. There were also some spaces before her last name and in the `id` field that I removed.

**Comment by kirstenkeister** [comment]
I've tested it on my local machine and her affiliation information shows up now, so I'll go ahead and close this. I've made a note to include this step in the Documentation.
